### ISSUE TITLE
Get the captured/matched results?

### ISSUE THREAD

**Issue by fidian** [isaacs/minimatch#105]
My goal is to rename files using a syntax similar to `mmv`.  Here's an example of how to use that tool:

    mmv 'folder/*.jpg' 'other-destination/#1.jpeg`

In order to make my library, I would really like to capture the matches for the various patterns. Assuming a filename of "test/documentation/module-controller.md", I would expect the following:

    // [ "module-controller.md" ]
    console.log(match("test/documentation/*"))

    // [ "test/documentation", "module-controller" ]
    console.log(match("**/*.md"));

    // [ "documentation", "module", "md" ]
    console.log(match("test/(doc*|lib*)/!(xxxx)*-controller.*"));

Is it easily possible to make the generated regular expressions capture these groups? My goal would be to avoid forking the repository and working with a published API when possible. I can get the regular expression but I'm having difficulty detecting the groups and converting them to capture.

Do you see this as something that could be added to your library?

**Comment by isaacs** [comment]
I'd worry that it might impact performance.  Minimatch specifically _doesn't_ capture match groups so that the RegExp engine can just discard them, which can be significantly faster.  (This becomes a bigger issue in glob and ignore-walk, where a bunch of minimatch comparisons are performed at a lower level against a large number of file system path portions.)

The other complicating issue might be just that those groups can be nested, which could get hairy, but I guess if you're crafting the pattern, that's on you to know what's what.

The capture semantics for extglobs is very straightforward.  It gets weird when you add in `{,}` groups and `*`, `**` and such.  For example:

```js
const f = 'a/b/c/d'
const p = '{a/**,*/b/*/*}'
console.log(match(f, p))
// ['b/c/d'] or ['a','c','d'] 🤔
// I guess just the first one it matched on?
```

Minimatch gives up when it finds the first match, since there's no need to test other patterns in the brace set.

**Comment by isaacs** [comment]
Yeah, I think this is not a great idea.  It's too confusing to work out the semantics of how it should work, and adding capture groups does make the regexps less efficient.  Probably better to just split the path yourself if you get a match.
