### ISSUE TITLE
"./*" pattern stopped working after upgrading from 6.2.0 to 7.0.0

### ISSUE THREAD

**Issue by ilyub** [isaacs/minimatch#198]
Pattern: ./*
String: ./source
Options: { dots: true }

Matches with 6.2.0, but stop matching after upgrading to 7.0.0

I have checked change log:
https://github.com/isaacs/minimatch/blob/main/changelog.md
but it does not mention any backward-incompatible changes related to single dot "."

Could you fix it if it is a bug?
And if it is expected, add some kind of migration instructions?

Thx for useful package.

**Comment by isaacs** [comment]
I'll have to think about a cleaner solution, but threw a kludge in there for the most common case.

This is a result of optimizing out all the `.` and `''` portions from a pattern, which does make things quite a bit faster in some cases, but also had this unintended side effect.

The kludge only looks for `'.'` exactly, which means that a pattern like `./*` won't match `.///foo`, which I think is also expected, but that'll have to be done a bit more carefully.

**Comment by ilyub** [comment]
Still not back-compatible for me. I am matching both "." and ".." in many places. But I will wait for cleaner solution and stay with 6.x version for now.

Thx again for the package.

**Comment by isaacs** [comment]
Yeah, I'll have to either resolve the file path as well using the same logic, or put the pattern condensing behind an opt in flag.

**Comment by isaacs** [comment]
> Yeah, I'll have to either resolve the file path as well using the same logic, or put the pattern condensing behind an opt in flag.

Decided to go ahead and do both.

Try with 7.1.0.  You can use the advanced optimizations which _should_ work fine by setting `{ optimizationLevel: 2 }` in the options, but the default `{ optimizationLevel: 1 }` was rolled back to the 6.2 behavior.

If the default is also a problem (because it _does_ do some resolutions of `..` portions), you can also use `{ optimizationLevel: 0 }`, and that'll be the same minimal optimizing behavior as minimatch v5.
