### ISSUE TITLE
Glob patterns with `**` are not properly converted to regular expressions

### ISSUE THREAD

**Issue by moretti** [isaacs/minimatch#67]
``` js
> minimatch('node_modules/foobar/foo.bar', 'node_modules/foobar/**/*.bar')
> true

> var re = minimatch.makeRe('node_modules/foobar/**/*.bar', { nocase: true });
/^(?:(?=.)node_modules\/(?=.)foobar\/(?:(?!(?:\/|^)\.).)*?\/(?!\.)(?=.)[^/]*?\.bar)$/i
> re.test('node_modules/foobar/foo.bar')
false
```

**Comment by mmraff** [comment]
Another example to support this issue:
```javascript
> var mmOpts = {
...         dot: true,
...         nobrace: true,
...         noext: true,
...         nocomment: true,
...         nonegate: true
...       }
undefined
> minimatch("filename.txt", "**/*.txt", mmOpts)
true
```
Properly, the slash after the globstar is non-negotiable.
An authoritative reference: http://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html

**Comment by isaacs** [comment]
So, here's the thing about this: what you're asking for is really hard, perhaps impossible, because glob expressions are not "regular" in quite the same sense that regular expressions are.

The RegExp that's generated by minimatch's makeRe method are not what node-glob or minimatch actually use for matching `**`, since `**` is intended to match the bash 4.3 behavior identically, and there's no way to do that with the a single regular expression using the engine in JavaScript.  (I'm told that it _is_ possible in Perl and using some compiled implementations, but one of the constraints of this module is that it not require any compiled dependencies.)

The double-star is tricky, and there's this edge case where it has to allow any or no directories, none of which can start with a `.`.  Check out the logic that actually handles this in pattern resolution, and you'll start to understand why.

If someone cleverer than me can adjust the regular expression generation such that it works in more cases, I'd be happy to accept a PR.  It seems like this should also go in the documentation of the makeRe function, so that it's less of a footgun, at least.

**Comment by mmraff** [comment]
Sorry, I thought I was sure that I canceled my comment, when I started
to anticipate what you have said. Seems like cancellation didn't go
through. Bad GitHub.

**Comment by isaacs** [comment]
@mmraff No worries!  Actually, I think what you'd posted is a valid bug, separate from this issue (which is about makeRe, not about the base match function).

**Comment by isaacs** [comment]
a979c06
