### ISSUE TITLE
2.0.8 -> 2.0.9 regression for weird nested *(!(pattern))

### ISSUE THREAD

**Issue by collingreen** [isaacs/minimatch#68]
The upgrade to 2.0.9 from 2.0.8 (which happened automatically for us on install with gulp -> vinyl-fs -> glob-stream -> minimatch) introduces a failure generating valid regexes for our pattern `src/**/*(*.json|!(*.js))`. Granted, that pattern is a bit wonky, but it was working before and now it is not.

I have a PR with the test added -- it passes on 2.0.8 but showcases the error in 2.0.9. I didn't pull against your master since it doesn't include a solution, just a failing test. 

https://github.com/weebygames/minimatch/pull/1

@isaacs - let me know if you want me to PR this against your master

**Comment by isaacs** [comment]
Indeed, this is a bug in the approach to simulating negative lookahead, in that it doesn't take into consideration that it should not copy close-parens coming after the pattern that match to open-parens from before the negative section.

Fix looks reasonable.  Will probably get to it soon.

**Comment by collingreen** [comment]
Great, thanks! Let me know if I can be helpful.

**Comment by isaacs** [comment]
I have a fix that avoids the broken regexp, but it has a bug in it, wrt the design intent of matching Bash 4.3's pattern syntax.

The glob pattern `*(*.json|!(*.js))` actually *should* match `foojs.js`!  Observe:

```
$ shopt -s extglob

$ if [[ foojs.js == *(*.json|!(*.js)) ]]; then echo ok; else echo nope; fi
ok

$ echo $BASH_VERSION
4.3.30(6)-release
```

However, with my fix, it doesn't:

```
$ node -p 'require("./")("foojs.js","*(*.json|!(*.js))")'
false
```

So, there's a bit of work to be done yet to sort that out.

I'm thinking it's probably still better, since it gives you the behavior you're actually expecting (albeit expecting incorrectly!) and avoids a crash.  However, be advised that this will be considered a known bug, and likely "fixed" pretty soon (which will probably make you unhappy).

**Comment by isaacs** [comment]
The reason it matches, btw, is that you're using `*()` instead of `@()` for the outermost pattern.

The star means "match zero or more of these items".  So, since it literally matches zero of them, and that's all that is there, the anchor that minimatch places against the start and end of the pattern is causing it to fail incorrectly.

**Comment by isaacs** [comment]
Oh, no, I think this is actually a bug in Bash.  `+(!(*.js))` matches a file `foo.js`, so something is definitely weird there.

I'm going to land the patch, but also continue to investigate this.  Expect a release shortly.

**Comment by isaacs** [comment]
Nevermind, this is actually working properly in Bash.  `+` means `1 or more times` and `*` means `zero or more times`, so `+(!(*.js))` matches `foo.j` against `!(*.js)` and then matches `s` against `!(*.js)`, and so it should be a match.  Ditto `*`, but `@` and `?` should in fact fail as they do.

**Comment by collingreen** [comment]
No matter what happens I won't be unhappy! I updated our pattern to be more simple and continue working -- just wanted to show the fail case. Sorry for the bogus test contents on my part.
