### ISSUE TITLE
testing true when reading negative match before *

### ISSUE THREAD

**Issue by zwhitchcox** [isaacs/minimatch#75]
for the glob `logic/{,**/}!(*.spec.sjs)*.sjs` it is matching `logic/user/user.spec.sjs`

also `logic/{,**/}*!(.spec.sjs).sjs` doesn't work either

if you look on globtester.com, though, it works

**Comment by isaacs** [comment]
This is working as intended, matching the behavior of bash 5.

```
$ mkdir -p logic/user

$ touch logic/user/user.spec.sjs

$ for i in logic/{,**/}*!(.spec.sjs).sjs; do echo $i; done
logic/*!(.spec.sjs).sjs
logic/user/user.spec.sjs

$ for i in logic/{,**/}!(*.spec.sjs)*.sjs; do echo $i; done
logic/!(*.spec.sjs)*.sjs
logic/user/user.spec.sjs

$ node -p 'require("./")("logic/user/user.spec.sjs", "logic/{,**/}!(*.spec.sjs)*.sjs")'
true

$ node -p 'require("./")("logic/user/user.spec.sjs", "logic/{,**/}*!(.spec.sjs).sjs")'
true
```

The pattern expands to:

- the literal string `"logic/"`, followed by
- either nothing, or zero or more path portions (note: `{,**/}` is unnecessary, since `**/` can match the empty string), followed by
- 1 or more non-dot or / chars that do not match `*.spec.sjs`, followed by
- zero or more non-/ characters not starting with a dot, followed by
- the literal string `".sjs"`

The path `logic/user/user.spec.sjs` matches this.

- `logic/` matches `logic/`
- `user/` matches `**`
- `u` matches 1 or more non-dot or / chars that do not match `*.spec.sjs`
- `ser.spec` matches zero or more non-/ characters not starting with a dot
- `.sjs` matches `.sjs`

Negative extglobs are not negative lookaheads applied to the rest of the pattern.  They work differently.  They're a negative lookahead in a non-captured group, with a `.+` following them.  Ie, `!(x)?` is not `/^(?!x).$/` but rather `/^(?:(?!x).).$/`.
